# Generated by Django 3.0 on 2020-01-07 20:19

from django.db import migrations, models
import mariokrat.models.tournament


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('admin_token', models.TextField(default=mariokrat.models.tournament.get_token)),
                ('spectator_token', models.TextField(default=mariokrat.models.tournament.get_token)),
            ],
        ),
    ]
