# Generated by Django 3.0 on 2020-01-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariokrat', '0007_cup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='cup',
            new_name='cup_number',
        ),
        migrations.AddField(
            model_name='race',
            name='cup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='mariokrat.Cup'),
        ),
        migrations.AlterField(
            model_name='race',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='mariokrat.Game'),
        ),
    ]
