# Generated by Django 3.0 on 2020-01-19 13:46

from django.db import migrations


def game_to_cup(apps, schema_editor):
    Cup = apps.get_model('mariokrat', 'Cup')
    Race = apps.get_model('mariokrat', 'Race')
    for race in Race.objects.all():
        cup, _ = Cup.objects.get_or_create(
            game=race.game,
            number=race.cup_number,
        )
        race.cup = cup
        race.save()


def cup_to_game(apps, schema_editor):
    Race = apps.get_model('mariokrat', 'Race')
    for race in Race.objects.all():
        race.game = race.cup.game
        race.cup_number = race.cup.number
        race.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mariokrat', '0008_race_cup'),
    ]

    operations = [
        migrations.RunPython(game_to_cup, cup_to_game),
    ]
