# Generated by Django 3.0 on 2020-01-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariokrat', '0009_race_autofill_cup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='race',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='race',
            name='cup_number',
        ),
        migrations.RemoveField(
            model_name='race',
            name='game',
        ),
        migrations.AlterField(
            model_name='race',
            name='cup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='mariokrat.Cup'),
        ),
    ]
