# Generated by Django 3.0.2 on 2020-02-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariokrat', '0010_race_remove_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
