# Generated by Django 3.0.2 on 2020-02-02 12:21

from django.db import migrations


def autofill_round(apps, schema_editor):
    Tournament = apps.get_model('mariokrat', 'Tournament')

    for tournament in Tournament.objects.all():
        games = set()
        round_number = 1

        round = True
        while round:
            round = {
                game
                for game in tournament.games.all()
                if game not in games and all(
                    slot.player is not None or slot.source in games
                    for slot in game.players_in.all()
                )
            }

            for game in round:
                game.round = round_number
                game.save()
                games.add(game)

            round_number += 1


class Migration(migrations.Migration):

    dependencies = [
        ('mariokrat', '0011_game_round'),
    ]

    operations = [
        migrations.RunPython(autofill_round, migrations.RunPython.noop),
    ]
