# Generated by Django 3.0.7 on 2020-12-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariokrat', '0012_game_autofill_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_cups',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_races',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_size',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
