FROM python:3.7-buster

RUN python -c 'import secrets; print(secrets.token_hex(32))' > /app_secret

RUN mkdir -p /app/media
VOLUME /app/media

RUN pip install -qU daphne==2.4.1

COPY . /app/src
WORKDIR /app/src

RUN pip install -qUr requirements.txt

EXPOSE 8000/tcp

ENTRYPOINT ["daphne"]
CMD ["-b", "0.0.0.0", "-p", "8000", "main.asgi:application"]
