# Node
FROM node:16.3 AS builder

RUN mkdir app
WORKDIR app

COPY frontend/package.json .
RUN yarn && yarn cache clean

COPY frontend/src src
COPY frontend/public public

RUN yarn build && yarn cache clean

# Nginx
FROM nginx:1.17.6

COPY web/nginx-prod.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build /app

EXPOSE 80/tcp
